"use client";

/**
 * Where a finding's remediation text came from.
 *
 * Fix advice generated by a language model is useful and occasionally wrong, and
 * an analyst about to run a command on a production host is entitled to know
 * which of those they are reading. Both pieces here exist for that:
 *
 * * `RemediationSourceChip` — a one-glance marker on the card, so nobody has to
 *   open a modal to find out whether a human wrote this.
 * * `RemediationProvenanceNote` — the full record next to the text itself: the
 *   model, its own stated confidence, and the things it said it could not
 *   determine. That last list is the most valuable part and the easiest to
 *   drop, so it is rendered in full rather than clamped.
 *
 * Nothing here is decorative. If provenance was never recorded — a finding from
 * before the feature, or one whose advice is the built-in template — these
 * render nothing at all rather than asserting a default.
 */

import { PencilIcon, SparkIcon } from "@/components/app/icons";
import { Chip } from "@/components/ui/Badge";
import { cn } from "@/lib/format";
import { isAiRemediation } from "@/lib/types";
import type { RemediationConfidence, RemediationProvenance } from "@/lib/types";

const SOURCE_LABEL: Record<RemediationProvenance["source"], string> = {
  claude: "AI fix",
  // Same model output, reused rather than regenerated for an identical CVE and
  // stack. Distinguished in the tooltip, not in the label — the difference is
  // about cost, and an analyst reading the advice does not care.
  "claude-cached": "AI fix",
  analyst: "Analyst",
  template: "Standard advice",
};

const SOURCE_TITLE: Record<RemediationProvenance["source"], string> = {
  claude: "Written by Claude from this host's observed services and versions.",
  "claude-cached": "Written by Claude for an identical CVE and stack, reused here.",
  analyst: "Edited by someone on your team, replacing any generated text.",
  template: "The built-in advice for this class of finding.",
};

const CONFIDENCE_LABEL: Record<RemediationConfidence, string> = {
  high: "High confidence",
  medium: "Medium confidence",
  low: "Low confidence",
};

/**
 * Confidence is the model's own claim about its output, so it is styled as a
 * caution, never as reassurance: low is tinted, high is not. A green "high
 * confidence" badge would be the machine marking its own work.
 */
const CONFIDENCE_TINT: Record<RemediationConfidence, string> = {
  high: "",
  medium: "border-warn-bg bg-warn-bg text-warn-fg",
  low: "border-warn-bg bg-warn-bg text-warn-fg",
};

export function RemediationSourceChip({
  provenance,
  className,
}: {
  provenance: RemediationProvenance;
  className?: string;
}) {
  const ai = isAiRemediation(provenance.source);
  return (
    <Chip className={cn("gap-1", className)}>
      <span title={SOURCE_TITLE[provenance.source]} className="inline-flex items-center gap-1">
        {ai ? <SparkIcon /> : provenance.source === "analyst" ? <PencilIcon /> : null}
        {SOURCE_LABEL[provenance.source]}
      </span>
    </Chip>
  );
}

export function RemediationProvenanceNote({
  provenance,
  className,
}: {
  provenance: RemediationProvenance;
  className?: string;
}) {
  const ai = isAiRemediation(provenance.source);

  return (
    <div className={cn("rounded border border-border bg-surface px-3 py-2", className)}>
      <div className="flex flex-wrap items-center gap-1.5">
        <RemediationSourceChip provenance={provenance} />
        {provenance.model ? (
          <span className="font-mono text-2xs text-muted">{provenance.model}</span>
        ) : null}
        {provenance.confidence && provenance.confidence !== "high" ? (
          <span
            className={cn(
              "inline-flex items-center rounded border px-1.5 py-0.5 text-2xs font-medium leading-4",
              CONFIDENCE_TINT[provenance.confidence],
            )}
          >
            {CONFIDENCE_LABEL[provenance.confidence]}
          </span>
        ) : null}
      </div>

      {ai ? (
        <p className="mt-1.5 text-xs leading-relaxed text-muted">
          Generated from the services and versions observed on this host. Verify the version
          numbers and package names against the host before running anything.
        </p>
      ) : null}

      {provenance.uncertain.length > 0 ? (
        <div className="mt-2 border-t border-border pt-2">
          <h5 className="text-2xs font-medium uppercase tracking-wide text-muted">
            Could not be determined
          </h5>
          <ul className="mt-1 flex flex-col gap-1">
            {provenance.uncertain.map((item) => (
              <li key={item} className="flex gap-1.5 text-xs leading-relaxed text-text">
                <span aria-hidden="true" className="text-muted">
                  &middot;
                </span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      ) : null}
    </div>
  );
}
